-- =============================================================================
-- Redo of the Salesforce accounts import (see import_2026-09-13_salesforce_accounts.sql).
-- The first pass used a non-ASCII dash character as a placeholder for blank
-- phone/contact/email fields, and that character got mangled into mojibake
-- somewhere between here and the database -- almost
-- certainly a charset mismatch in the SQL Editor's paste/execute path. This
-- deletes exactly the rows the first import created (matched by name, scoped
-- to that import's date so nothing else is touched) and re-inserts the same
-- data with a plain-ASCII placeholder ("needs to be filled") that cannot suffer
-- the same corruption.
-- =============================================================================

delete from leads
 where brand = 'epay'
   and converted_at = '2026-09-13'
   and business_name in (
    'A1 SMOKES & VAPES',
    'A1 smokes and vapes',
    'Afzal and Shah LLC',
    'AL RAYAHIN BAKERY AND SW',
    'Allergy clinic',
    'Ann Routon',
    'Anna nails LLC',
    'AOK APPLIANCES',
    'asads friend halal market',
    'ATM solutions',
    'AZRL LLC',
    'Detroit nails inc',
    'Elite nails',
    'Envision Processing',
    'Expert nails',
    'Expert nails and spa',
    'Faris LLC',
    'finest halal market',
    'Fun zone smoke shop',
    'G and S market',
    'GIGI''S NAILS',
    'grand rapids c store',
    'Howell Nail & Spa LLC',
    'J Rose Wholesale Flowers Corp',
    'Jacks Pub',
    'Laxmi Fuel 2 Inc',
    'Lexann dental',
    'Lord of vapes',
    'Loyalty Tattoo',
    'MACOMB APPLIANCE',
    'MADINA HALAL MARKET',
    'Majed Zaza',
    'Moore CSP LLC',
    'Motel 6',
    'Mount plesant vending',
    'nail salon',
    'Nails spa VI llc',
    'Padma Hospitality LLC',
    'PHO HANOI',
    'Pho Hanoi',
    'Pho street',
    'Q BAKING CORNER',
    'Richmond Township Community Club',
    'Sans succi',
    'shree hospitality',
    'small town diner',
    'SYCOS CYCLES',
    'treasure hunt liquidation',
    'Troy Days',
    'UP bar',
    'VICTORIAS JEWELRY',
    'Wanderlust LLC/the glass money',
    'Infinity guardianship',
    'Mentors of Michigan'
  );

delete from leads
 where brand = 'atm'
   and converted_at = '2026-09-13'
   and business_name in (
    '4 location ATM liqour store lead',
    '8 mile nail salon',
    '[not provided]',
    '[not provided]',
    '[not provided]',
    '[not provided]',
    '[not provided]',
    '[not provided]',
    '[not provided]',
    '[not provided]',
    '[not provided]',
    '[not provided]',
    '[not provided]',
    'Al Karrada Barbershop',
    'Angel Brant',
    'Ann arbor nails',
    'Autumn Moultrie',
    'Balaram reddy Panumati',
    'Barbershop',
    'Battle creek nails 2',
    'Bay spa',
    'BH nail salon westland',
    'BH nails salon',
    'Big rapids nail salon',
    'bliss nails Northville',
    'Bloom nail salon',
    'Bloom nails and spa',
    'Bloomfield nails and spa',
    'C store',
    'C store grand rapids',
    'cannabis cashier',
    'Church Festival',
    'CJ berrymores',
    'Coco nails',
    'Coconut creek massage',
    'common appliance',
    'community center',
    'Designer nails',
    'Designer Nails Howell',
    'DL nails flat rock 2',
    'eagle nails',
    'Eddie Chang',
    'elite bankcard services',
    'Eric Lindemann',
    'Essex gas station',
    'Evelyn Nguyen',
    'Farmington hills nails',
    'Ferndale nail bar DET',
    'ferndale nail salon',
    'Florida gas station bundle',
    'Fly fishing event',
    'Gas station',
    'gas stations',
    'GB guy Roseville nail salon',
    'gorgeous nails',
    'Gorse pointe MI Nails 2',
    'Grand river barber company',
    'gratiot pub',
    'grosbeak nails',
    'grosebeck app store',
    'Harsens island non profit',
    'Hello nail and lashes',
    'imlay plaza new nail salon',
    'Jackson nail salon',
    'Jailhosue cannabis',
    'Jailhouse #3',
    'Jailhouse canna Kalkaska',
    'ken nails and spa',
    'Kings nails',
    'kings nails',
    'Kings nails 2',
    'lakeland massage',
    'Laundromat in Baldwin MI',
    'Liqour store north Chicago',
    'Livonia nail salon',
    'Love nails and spa',
    'Lovely nails',
    'Lucky spa & nails',
    'luna Fuels',
    'luxary nails and spa',
    'M30 liquor store',
    'Marine shop',
    'massage spa fort Lauderdale',
    'mi gorcery store',
    'Mi nails',
    'Mi nails 4th location in Roseville',
    'Micro cannabis New Mexico',
    'Milford tattoo shop',
    'multiple hotel owner',
    'Nail salon in ferndale',
    'nail salon in portage',
    'new bar location up north',
    'new chicago location',
    'New Nails and spa',
    'new Waterford nail salon',
    'New York Barber shop',
    'Norton shores nail salon',
    'Olusola Rotimi',
    'Orchid nails',
    'orlando massage spa',
    'Pink lotus spa',
    'Platinum nails and spa',
    'Pointes center',
    'Poker room Sandusky',
    'Pontiac nails',
    'Private club bay city',
    'Queens nails',
    'Richmond nails',
    'Roscommon dispo',
    'Roseville nail salon',
    'Roseville nails',
    'roseville nails and spa',
    'shekhar karki',
    'Shelby nails new',
    'Sperrys movie house',
    'Spraders on the lake',
    'Sterling Heights nail salon',
    'sterling heights nail salon',
    'Tattoo shop',
    'Tattoo studio',
    'TEST IT',
    'Traxside Bar',
    'Trish Nails Hastings MI',
    'unlimited ATMs',
    'UP bar',
    'VA Shell and mobile',
    'varsity jacket location',
    'VIP nails and spa',
    'West palm beach spa',
    'Wyndham hotels',
    'ypslinati nails',
    'ATM start up',
    'ATM startup',
    'Chris M North Carolina and more',
    'Cindy vaulter',
    'Dash ATM',
    'E.G.Nick''s Agostini',
    'Elvis florida ATM startup',
    'Fraser bloomfield nails and spa',
    'Gianni FL',
    'Jason Downs',
    'Jeff Burton ATMs',
    'Lilly Cash co',
    'Luis Choice one ATM',
    'MCC event for TARA gymnastics',
    'Micheal breckendige',
    'micheal leadford MBS financial',
    'Power ATM',
    'Robert gun show event',
    'rolly receipts',
    'rundash cash'
  );

delete from cold_leads
 where brand = 'epay'
   and created_at = '2026-09-13'
   and source_category = 'hand_entered'
   and business_name in (
    'Acme POS',
    'Grocery store location',
    'grooming business',
    'Hanif Resturant lead',
    'Schoolhouse',
    'Smoking hut',
    'south florida resturant',
    'Suoer 8 wyndham',
    'Texan Liquor',
    'WA new shop',
    'WA restaurant',
    'Zaitoon Bakery and Grocery Store',
    'Il smoke shop',
    'New york smoke shop'
  );

insert into leads (
  brand, business_name, contact_name, phone, email, business_address,
  stage, atm_stage, converted_to_account, converted_at
) values
  ('epay', 'A1 SMOKES & VAPES', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'A1 smokes and vapes', 'needs to be filled', '(612) 707-5252', 'needs to be filled', 'Brooklyn Park, MN', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Afzal and Shah LLC', 'needs to be filled', '(206) 832-9041', 'naseer.yusufi@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'AL RAYAHIN BAKERY AND SW', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Allergy clinic', 'needs to be filled', '(971) 867-9716', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Ann Routon', 'needs to be filled', '(580) 812-3055', 'amaxnat@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Anna nails LLC', 'needs to be filled', '(248) 797-2112', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'AOK APPLIANCES', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'asads friend halal market', 'needs to be filled', '(713) 429-3529', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'ATM solutions', 'needs to be filled', '(203) 939-2203', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'AZRL LLC', 'needs to be filled', '(203) 333-8273', 'zaman3027@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Detroit nails inc', 'needs to be filled', '(248) 659-2766', 'needs to be filled', 'Detroit, MI', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Elite nails', 'needs to be filled', '(248) 797-2112', 'needs to be filled', 'Hazel Park, MI', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Envision Processing', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Expert nails', 'needs to be filled', '(810) 316-0320', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Expert nails and spa', 'needs to be filled', '(585) 567-3678', 'needs to be filled', 'Howell, MI', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Faris LLC', 'needs to be filled', '(203) 723-5000', 'farhadkhan800@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'finest halal market', 'needs to be filled', '(253) 478-9370', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Fun zone smoke shop', 'needs to be filled', '(209) 827-6433', 'funzoneheadshop@gmail.com', 'Los Banos, CA', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'G and S market', 'needs to be filled', '(773) 332-5817', 'gssupermarketshop@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'GIGI''S NAILS', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'grand rapids c store', 'needs to be filled', '(616) 550-8387', 'samberdan.alger@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Howell Nail & Spa LLC', 'needs to be filled', '(517) 545-9402', 'james090888@yahoo.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'J Rose Wholesale Flowers Corp', 'needs to be filled', '(212) 564-0400', 'troy@jrosewfl.net', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Jacks Pub', 'needs to be filled', '(248) 632-3534', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Laxmi Fuel 2 Inc', 'needs to be filled', '(954) 740-3673', 'litan.majumder14@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Lexann dental', 'needs to be filled', '(408) 858-1624', 'needs to be filled', 'San Jose, CA', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Lord of vapes', 'needs to be filled', '(330) 987-0098', 'blackcoins425@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Loyalty Tattoo', 'needs to be filled', '(810) 265-8827', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'MACOMB APPLIANCE', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'MADINA HALAL MARKET', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Majed Zaza', 'needs to be filled', '(209) 710-8309', 'majedzaza@hotmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Moore CSP LLC', 'needs to be filled', '(248) 375-3388', 'moore@classic-shipping.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Motel 6', 'needs to be filled', '(425) 389-0052', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Mount plesant vending', 'needs to be filled', '(989) 289-0054', 'parammpatel06@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'nail salon', 'needs to be filled', '(248) 854-5626', 'needs to be filled', 'Wyandotte, MI', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Nails spa VI llc', 'needs to be filled', '(586) 323-6009', 'needs to be filled', 'Utica, MI', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Padma Hospitality LLC', 'needs to be filled', '(209) 272-1455', 'jetinnmotel3747@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'PHO HANOI', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Pho Hanoi', 'needs to be filled', '(248) 307-7775', 'alicetran0303@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Pho street', 'needs to be filled', '(248) 832-3888', 'moctra0622@gmail.com', 'MI', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Q BAKING CORNER', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Richmond Township Community Club', 'needs to be filled', '(906) 475-4725', 'rtcc2020@outlook.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Sans succi', 'needs to be filled', '(586) 306-4305', 'schweikartka@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'shree hospitality', 'needs to be filled', '(425) 389-0052', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'small town diner', 'needs to be filled', '(580) 465-8746', 'amaxnat@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'SYCOS CYCLES', 'needs to be filled', '(618) 451-7974', 'sycoscycles@gmail.com', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'treasure hunt liquidation', 'needs to be filled', '(253) 246-9279', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Troy Days', 'needs to be filled', '(586) 491-5096', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'UP bar', 'needs to be filled', '(906) 362-1476', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'VICTORIAS JEWELRY', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Wanderlust LLC/the glass money', 'needs to be filled', '(859) 663-5630', 'needs to be filled', 'Covington, KY', 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Infinity guardianship', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13'),
  ('epay', 'Mentors of Michigan', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'converted_active', 'inbound_placement', true, '2026-09-13');

insert into leads (
  brand, business_name, contact_name, phone, email, business_address,
  stage, atm_stage, converted_to_account, converted_at
) values
  ('atm', '4 location ATM liqour store lead', 'needs to be filled', '(406) 425-7467', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '8 mile nail salon', 'needs to be filled', 'needs to be filled', 'needs to be filled', 'Oak Park, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', 'needs to be filled', 'testdemo@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(979) 422-6759', 'themainstore25@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(810) 614-5414', 'troylu948@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(954) 213-2480', 'mtmotiur48@gmail.com', 'Hollywood, FL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(770) 862-4629', 'horsemaniac01@yahoo.com', 'Butler, GA', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(517) 750-8703', 'larryharrissr@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(936) 933-6060', 'krsimon101702@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(989) 933-6925', 'nabirchowdhury@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(716) 474-4006', 'ndigangi330@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(541) 735-5446', 'cndrust@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', '[not provided]', 'needs to be filled', '(616) 666-5567', 'midieule96@gmai.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Al Karrada Barbershop', 'needs to be filled', '(773) 312-0440', 'needs to be filled', 'Arlington Heights, IL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Angel Brant', 'needs to be filled', '(205) 353-6500', 'da_brant@yahoo.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Ann arbor nails', 'needs to be filled', '(734) 626-5549', 'needs to be filled', 'Livonia, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Autumn Moultrie', 'needs to be filled', '(347) 543-2981', 'autumn@backalleybread.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Balaram reddy Panumati', 'needs to be filled', '(973) 953-1911', 'smokebarrel0789@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Barbershop', 'needs to be filled', '(269) 808-2487', 'needs to be filled', 'Kalamazoo, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Battle creek nails 2', 'needs to be filled', '(269) 213-1980', 'c.m.huyn@gmail.com', 'Battle Creek, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Bay spa', 'needs to be filled', '(561) 523-6250', 'needs to be filled', 'Stafford Township, NJ', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'BH nail salon westland', 'needs to be filled', '(586) 272-5180', 'needs to be filled', 'Westland, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'BH nails salon', 'needs to be filled', '(586) 272-5180', 'needs to be filled', 'St. Clair Shores, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Big rapids nail salon', 'needs to be filled', '(586) 305-9493', 'needs to be filled', 'Big Rapids, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'bliss nails Northville', 'needs to be filled', '(248) 797-2112', 'needs to be filled', 'Northville, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Bloom nail salon', 'needs to be filled', '(256) 535-5506', 'needs to be filled', 'Monroe, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Bloom nails and spa', 'needs to be filled', '(248) 797-2112', 'needs to be filled', 'Auburn Hills, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Bloomfield nails and spa', 'needs to be filled', '(504) 331-9724', 'needs to be filled', 'MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'C store', 'needs to be filled', '(216) 280-5137', 'needs to be filled', 'Cleveland, OH', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'C store grand rapids', 'needs to be filled', '(616) 550-8387', 'samberdan.alger@gmail.com', 'Grand Rapids, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'cannabis cashier', 'needs to be filled', '(253) 310-6703', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Church Festival', 'needs to be filled', '(586) 747-0030', 'stefgeorge@kw.com', 'Troy, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'CJ berrymores', 'needs to be filled', '(847) 400-7479', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Coco nails', 'needs to be filled', '(248) 854-5626', 'needs to be filled', 'Wyandotte, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Coconut creek massage', 'needs to be filled', '(954) 806-6211', 'needs to be filled', 'Coconut Creek, FL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'common appliance', 'needs to be filled', '(586) 879-1193', 'needs to be filled', 'Roseville, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'community center', 'needs to be filled', '(989) 621-5783', 'leysue678@gmail.com', 'Farwell, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Designer nails', 'needs to be filled', '(810) 991-1239', 'needs to be filled', 'Howell, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Designer Nails Howell', 'needs to be filled', '(586) 567-3678', 'needs to be filled', 'Howell, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'DL nails flat rock 2', 'needs to be filled', '(248) 325-4849', 'needs to be filled', 'Trenton, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'eagle nails', 'needs to be filled', '(586) 219-3747', 'needs to be filled', 'Southfield, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Eddie Chang', 'needs to be filled', '(989) 298-3118', 'otp.asianmarket@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'elite bankcard services', 'needs to be filled', '(734) 775-7400', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Eric Lindemann', 'needs to be filled', '(631) 873-7417', 'ericlindemann631@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Essex gas station', 'needs to be filled', '(860) 869-6696', 'needs to be filled', 'Essex, CT', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Evelyn Nguyen', 'needs to be filled', '810881368', 'diamondnailsmidland@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Farmington hills nails', 'needs to be filled', '(586) 488-8114', 'needs to be filled', 'Farmington Hills, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Ferndale nail bar DET', 'needs to be filled', '(286) 224-6868', 'needs to be filled', 'Highland Park, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'ferndale nail salon', 'needs to be filled', '(248) 797-2112', 'needs to be filled', 'Ferndale, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Florida gas station bundle', 'needs to be filled', '(305) 336-4314', 'needs to be filled', 'St. Augustine, FL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Fly fishing event', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Gas station', 'needs to be filled', '(989) 289-0054', 'parammpatel06@gmail.com', 'Huntsville, AL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'gas stations', 'needs to be filled', '(336) 244-1875', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'GB guy Roseville nail salon', 'needs to be filled', '(586) 305-9493', 'needs to be filled', 'Roseville, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'gorgeous nails', 'needs to be filled', '(586) 215-4506', 'needs to be filled', 'Chesterfield, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Gorse pointe MI Nails 2', 'needs to be filled', '(248) 632-2071', 'needs to be filled', 'Grosse Pointe, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Grand river barber company', 'needs to be filled', '(517) 582-2371', 'needs to be filled', 'East Lansing, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'gratiot pub', 'needs to be filled', '(248) 632-3534', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'grosbeak nails', 'needs to be filled', '(504) 331-9724', 'needs to be filled', 'MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'grosebeck app store', 'needs to be filled', '(586) 879-1193', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Harsens island non profit', 'needs to be filled', '(586) 306-4305', 'needs to be filled', 'Harsens Island, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Hello nail and lashes', 'needs to be filled', '(248) 794-3507', 'pjnguyen04@gmail.com', 'Flint, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'imlay plaza new nail salon', 'needs to be filled', '(734) 419-1452', 'needs to be filled', 'Detroit, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Jackson nail salon', 'needs to be filled', '(248) 797-2112', 'needs to be filled', 'Jackson, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Jailhosue cannabis', 'needs to be filled', '0', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Jailhouse #3', 'needs to be filled', '(989) 916-7701', 'needs to be filled', 'Mio, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Jailhouse canna Kalkaska', 'needs to be filled', '(989) 916-7701', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'ken nails and spa', 'needs to be filled', '(248) 536-2567', 'needs to be filled', 'Livonia, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Kings nails', 'needs to be filled', '(248) 797-2112', 'matthew@envisioninnovation.org', 'Oak Park, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'kings nails', 'needs to be filled', '(586) 489-8149', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Kings nails 2', 'needs to be filled', '(586) 489-8149', 'needs to be filled', 'Detroit, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'lakeland massage', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Laundromat in Baldwin MI', 'needs to be filled', '(517) 291-0029', 'needs to be filled', 'Baldwin, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Liqour store north Chicago', 'needs to be filled', '(773) 332-5817', 'needs to be filled', 'Chicago, IL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Livonia nail salon', 'needs to be filled', '(248) 797-2112', 'needs to be filled', 'Livonia, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Love nails and spa', 'needs to be filled', '(248) 739-3779', 'needs to be filled', 'Oak Park, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Lovely nails', 'needs to be filled', '(810) 732-4200', 'needs to be filled', 'Flint, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Lucky spa & nails', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'luna Fuels', 'needs to be filled', '(813) 369-4246', 'rock4incil@gmail.com', 'Coral Springs, FL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'luxary nails and spa', 'needs to be filled', '(840) 222-6789', 'needs to be filled', 'Highland Park, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'M30 liquor store', 'needs to be filled', '(347) 484-8918', 'needs to be filled', 'Edenville, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Marine shop', 'needs to be filled', '(989) 289-0054', 'needs to be filled', 'MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'massage spa fort Lauderdale', 'needs to be filled', '(561) 523-6250', 'needs to be filled', 'Fort Lauderdale, FL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'mi gorcery store', 'needs to be filled', '(586) 504-0061', 'needs to be filled', 'Sterling Heights, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Mi nails', 'needs to be filled', '(248) 632-2071', 'matthew@envisioninnovation.org', 'Grosse Pointe Woods, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Mi nails 4th location in Roseville', 'needs to be filled', '(248) 632-2071', 'needs to be filled', 'Roseville, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Micro cannabis New Mexico', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Milford tattoo shop', 'needs to be filled', '(248) 318-4129', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'multiple hotel owner', 'needs to be filled', '(904) 563-3462', 'staceyam111@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Nail salon in ferndale', 'needs to be filled', '(248) 399-1588', 'needs to be filled', 'Ferndale, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'nail salon in portage', 'needs to be filled', '(269) 440-3699', 'needs to be filled', 'Portage, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'new bar location up north', 'needs to be filled', '(989) 916-7701', 'needs to be filled', 'Mancelona, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'new chicago location', 'needs to be filled', '(312) 731-8167', 'needs to be filled', 'Chicago, IL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'New Nails and spa', 'needs to be filled', '(734) 582-4075', 'needs to be filled', 'Canton, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'new Waterford nail salon', 'needs to be filled', '(248) 674-2057', 'needs to be filled', 'MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'New York Barber shop', 'needs to be filled', '(518) 316-6775', 'nicholasruggiero8@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Norton shores nail salon', 'needs to be filled', '(231) 327-1818', 'needs to be filled', 'Norton Shores, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Olusola Rotimi', 'needs to be filled', '(984) 363-5506', 'olusolarotimi@ymail.com', 'Graham, NC', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Orchid nails', 'needs to be filled', '(586) 330-2005', 'needs to be filled', 'New Baltimore, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'orlando massage spa', 'needs to be filled', '(407) 250-6390', 'needs to be filled', 'Orlando, FL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Pink lotus spa', 'needs to be filled', '(626) 866-4081', 'needs to be filled', 'Fort Lauderdale, FL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Platinum nails and spa', 'needs to be filled', '(616) 450-8437', 'needs to be filled', 'Byron Center, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Pointes center', 'needs to be filled', '(724) 884-5925', 'needs to be filled', 'Holly, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Poker room Sandusky', 'needs to be filled', '(419) 366-4850', 'shipitpokersandusky@gmail.com', 'Sandusky, OH', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Pontiac nails', 'needs to be filled', '(586) 443-8045', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Private club bay city', 'needs to be filled', '(989) 891-7184', 'daveoberdorf@yahoo.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Queens nails', 'needs to be filled', '(248) 946-6221', 'needs to be filled', 'Ferndale, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Richmond nails', 'needs to be filled', '(734) 419-1452', 'needs to be filled', 'Richmond, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Roscommon dispo', 'needs to be filled', '(989) 312-0620', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Roseville nail salon', 'needs to be filled', '(586) 272-5180', 'needs to be filled', 'Roseville, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Roseville nails', 'needs to be filled', '(586) 272-5180', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'roseville nails and spa', 'needs to be filled', '(248) 797-2112', 'needs to be filled', 'Roseville, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'shekhar karki', 'needs to be filled', '(443) 838-6003', 'shekharjungkarki@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Shelby nails new', 'needs to be filled', '(248) 828-6339', 'needs to be filled', 'MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Sperrys movie house', 'needs to be filled', '(616) 566-0039', 'needs to be filled', 'Holland, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Spraders on the lake', 'needs to be filled', '(248) 640-2694', 'needs to be filled', 'MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Sterling Heights nail salon', 'needs to be filled', '(586) 354-3571', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'sterling heights nail salon', 'needs to be filled', '(586) 531-1958', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Tattoo shop', 'needs to be filled', '(248) 949-0285', 'needs to be filled', 'Southfield, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Tattoo studio', 'needs to be filled', '(989) 256-2682', 'needs to be filled', 'Beaverton, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'TEST IT', 'needs to be filled', '123123', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Traxside Bar', 'needs to be filled', '(567) 230-0215', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Trish Nails Hastings MI', 'needs to be filled', '(616) 881-9138', 'needs to be filled', 'Hastings, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'unlimited ATMs', 'needs to be filled', '(213) 932-8263', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'UP bar', 'needs to be filled', '(906) 362-1476', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'VA Shell and mobile', 'needs to be filled', '(703) 434-1400', 'paulbrar01@yahoo.com', 'Sterling, VA', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'varsity jacket location', 'needs to be filled', '(734) 493-2415', 'needs to be filled', 'Flat Rock, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'VIP nails and spa', 'needs to be filled', '(517) 303-6106', 'needs to be filled', 'Lansing, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'West palm beach spa', 'needs to be filled', '(786) 571-1772', 'needs to be filled', 'West Palm Beach, FL', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Wyndham hotels', 'needs to be filled', '(616) 835-4379', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'ypslinati nails', 'needs to be filled', '(714) 719-7171', 'needs to be filled', 'Ypsilanti, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'ATM start up', 'needs to be filled', '(989) 820-6532', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'ATM startup', 'needs to be filled', '(248) 224-7716', 'rasheednewton121@gmail.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Chris M North Carolina and more', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Cindy vaulter', 'needs to be filled', '(503) 438-0654', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Dash ATM', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'E.G.Nick''s Agostini', 'needs to be filled', '(248) 895-3736', 'needs to be filled', 'Plymouth, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Elvis florida ATM startup', 'needs to be filled', '(305) 462-8393', 'elvis.chorens@icloud.com', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Fraser bloomfield nails and spa', 'needs to be filled', '(248) 797-2112', 'needs to be filled', 'Fraser, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Gianni FL', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Jason Downs', 'needs to be filled', '(406) 425-7467', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Jeff Burton ATMs', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Lilly Cash co', 'needs to be filled', '(517) 902-4846', 'needs to be filled', 'Adrian, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Luis Choice one ATM', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'MCC event for TARA gymnastics', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Micheal breckendige', 'needs to be filled', '(989) 448-9703', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'micheal leadford MBS financial', 'needs to be filled', '(989) 488-9703', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Power ATM', 'needs to be filled', '(630) 414-2483', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'Robert gun show event', 'needs to be filled', '(810) 858-0079', 'needs to be filled', 'Sterling Heights, MI', 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'rolly receipts', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13'),
  ('atm', 'rundash cash', 'needs to be filled', 'needs to be filled', 'needs to be filled', NULL, 'inbound_lead', 'installation', true, '2026-09-13');

insert into cold_leads (
  brand, business_name, contact_name, phone, email, address,
  temperature, source_category, source
) values
  ('epay', 'Acme POS', 'needs to be filled', '(724) 884-5925', 'needs to be filled', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'Grocery store location', 'needs to be filled', '(858) 242-9176', 'needs to be filled', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'grooming business', 'needs to be filled', '(826) 208-9525', 'needs to be filled', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'Hanif Resturant lead', 'needs to be filled', '(425) 525-9630', 'needs to be filled', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'Schoolhouse', 'needs to be filled', '(810) 357-2593', 'islandgrille09@yahoo.com', 'Harsens Island, MI', 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'Smoking hut', 'needs to be filled', '(347) 735-7963', 'needs to be filled', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'south florida resturant', 'needs to be filled', '(954) 249-9893', 'needs to be filled', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'Suoer 8 wyndham', 'needs to be filled', '(631) 877-4776', 'saicorporation23@gmail.com', 'Monee, IL', 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'Texan Liquor', 'needs to be filled', '(281) 914-6300', 'texanliquorstore@yahoo.com', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'WA new shop', 'needs to be filled', '(206) 698-7829', 'alham8530@gmail.com', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'WA restaurant', 'needs to be filled', '(206) 571-3010', 'needs to be filled', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'Zaitoon Bakery and Grocery Store', 'needs to be filled', '(206) 765-8805', 'needs to be filled', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'Il smoke shop', 'needs to be filled', '(630) 267-2307', 'needs to be filled', 'Wheaton, IL', 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review'),
  ('epay', 'New york smoke shop', 'needs to be filled', '(412) 452-1458', 'needs to be filled', NULL, 'cold', 'hand_entered', 'Imported from Salesforce export - flagged for manual review');
